### ISSUE TITLE
Features/UI Breakdown 

### ISSUE THREAD

**Issue by SupriyaGadigone** [sysc4806/SYSC4806-WDWH#11]
I think the project description wants this as a UI: 
1.  In the first page the user enters, a dropdown list for year and program can be setup
2.  Once both are selected and user hits Submit
   -  The categories
   -  Learning outcomes in the category 
   - All courses in a given category
   - All learning outcomes on a given course
3.  Beside each of the row or table, there would be an edit option for the admin - How would we differentiate between a user and admin? Do we need a login for this?

**Comment by K-shamG** [comment]
We can also use AJAX to have the submit automatically update the page without refreshing it

**Comment by K-shamG** [comment]
We have two options for users that I can think of: 
1. Have user accounts for everyone and therefore set roles from there. This would require a user table and checking of permissions to determine which page they get sent to (editable or not). This would also have the potential for having users save preferences for their account, but this would add another feature/complexity to deal with. 

2. Have an admin login only so if they click on an admin button, they have to login and get sent to the editable page. If not, they are essentially treated as a guest and can just access the basic GUI for the app. The would remove the option for the extra feature of saving to the account and simplify things. Users can just go to the app, quickly check and not have to worry. (This could work with number 1 by allowing users to use the app without logging).

**Comment by RyanWork** [comment]
> 
> 
> We have two options for users that I can think of:
> 
>     1. Have user accounts for everyone and therefore set roles from there. This would require a user table and checking of permissions to determine which page they get sent to (editable or not). This would also have the potential for having users save preferences for their account, but this would add another feature/complexity to deal with.
> 
>     2. Have an admin login only so if they click on an admin button, they have to login and get sent to the editable page. If not, they are essentially treated as a guest and can just access the basic GUI for the app. The would remove the option for the extra feature of saving to the account and simplify things. Users can just go to the app, quickly check and not have to worry. (This could work with number 1 by allowing users to use the app without logging).

I think overall it would be better to implement number one. We may have intermediary roles in the future. If this does take off, maybe certain people have access to certain features that are not just strictly guest/admin.

We can, however, try and implement number two just by having two roles at first. Guest/Admin. I don't know if you guys agree. I don't think it should be too hard though. We wouldn't be the first to try and implement a login system in Spring Boot.

**Comment by SupriyaGadigone** [comment]
I think trying number 2 for now would be better since we always have the flexibility to move to 1 from there. But overall for the future 1 is better I agree.

**Comment by adamstaples** [comment]
> I think trying number 2 for now would be better since we always have the flexibility to move to 1 from there. But overall for the future 1 is better I agree.

I agree with Supriya, plus an login system seems like a pretty popular functionality that we might be able to just import and implement easily.

**Comment by SupriyaGadigone** [comment]
I am trying to work on some basic UI for the application and as per the UI breaking it down into Features, DB’s needed and use cases so after we can write everything down in the right issues and get programming soon, just made it easier or me to organize it this way: https://docs.google.com/document/d/18qV4hYCnySDYaes7utWehgLtyr86n1whkJopnsd8fpk/edit?usp=sharing

I was just curious if anyone had any ideas on how we would show all the information when a user selects the year and the program. I don’t think one table will cut it, not sure though?

I found this website with 2 dropdown's and though it looked cool: https://www.south.edu/programs/?fwp_location=asheville&fwp_degree_level=associate

They have links going to other pages after though. Not sure if that will work for us cause the user needs to have the ability to export the results.

**Comment by K-shamG** [comment]
I've done some rough sketches of what I think the UI should look like and here's what I came up with. It was tricky because there is so much data so I'm definitely open to suggestions and ideas. 

I was thinking the top of the page would look like this: 

![image](https://user-images.githubusercontent.com/15951317/53036222-46fec400-3445-11e9-8ff1-30cf3995bae3.png)
So you would select the program and year, but you can also filter those results based on course and category. This way, your CSV contains only the courses and categories you want. Also, the course multi-select would be populated after hitting submit (lists courses for that program from that year so you don't have to look through a million courses). 

Next would be the display table. I was thinking it would show the course and categories associated with it. The only problem with this is this table could become quite wide since there are 8 courses at least, per year. (We could consider filtering by semester or showing two tables for fall and winter, etc). 

![image](https://user-images.githubusercontent.com/15951317/53036322-862d1500-3445-11e9-8926-7642aa2126c8.png)

Then when you click on a category within a course, you can see the learning outcomes associated. 

![image](https://user-images.githubusercontent.com/15951317/53036435-c12f4880-3445-11e9-9f6e-68ca32fe53bb.png)

Finally, when you want to export by CSV there is the button at the top to export your current program, year and filter selections. From there, you should be able to pick which columns you want to show up in your CSV. My solution to that was creating a simple form upon clicking "Export". 
![image](https://user-images.githubusercontent.com/15951317/53036537-ee7bf680-3445-11e9-9002-e5a3d6fdbb12.png)
Here, you can check or uncheck columns you want to show up and then click export and the file should just download to your computer. 

(Whole sketch file here: https://drive.google.com/open?id=1aiTNQWXCWxqQmKRkqDpJP0ySx5Oba5Mp)

**Comment by K-shamG** [comment]
Features/Issues
- create models and controllers
- connect to models DB
- populate DB's with starter info
- display info for program/year
- change info upon submit
- filtering 
- export to CSV
- HTML UI design

**Comment by andrewdlqnguyen** [comment]
I agree with Supriya on doing 2 for simplicity then 1 after for future usability. 
Giving users its role as guest or admin on login would be less inconvenient for those logging in as admin (the system should know the login is an admin by checking privileges to allow an alternative selection for possible edit) then having them log in again to prove their admin for edit. 

Example/ admin login will see the GUI as a regular guest view but with a "pencil icon"  in the corner for edit on specific sections and guest login will have that icon invisible. This can be easily made i believe by giving them two different classes guest/admin and that alters the UI on login. 

I also like the idea of filter in kshamina's sketch. To add on, I think the Filter should open up a box with more choices of filtering like:
 Course year 1xxx - 4xxx (drag selection range tool)
 Category type
 Semester.
 Course or Category ID.

Can include an arrange filter for the table display (optional)
Show course: Alphabet, SYSC code ascending/descending, semester.

To shorten the table, we could show a simple view of each list with color coded initial categories per course that way the table wouldn't be so large and when pressed, it expands with everything.
Example/ Course: SYSC 1005
                LO: OO(red), Py(blue), SArch(pink) - expand: Object Oriented, Python, Software Architecture.

Color code initials could help quickly find similar categories from the other courses listed.

Hope these ideas help with the UI/UX.

**Comment by K-shamG** [comment]
I think we have enough of a basic idea to close this issue. We can revisit the UI during iteration 2 when we start to add styling.
